image: 'node:latest'
cache:
  paths:
    - node_modules/
stages:
  - build
  - deploy
build-dev:
  stage: build
  tags:
    - staging
  script:
    - npm install
    - npm run web-build-prod
  only:
    - staging
deploy-dev:
  tags:
    - staging
  only:
    - staging
  stage: deploy
  script:
    - ls
    - pwd
    - cd /home/gitlab-runner/builds/a63fa2eb/0/SDM/actproject/
    - pm2 restart server.js --env=production   --name "ActNursesPortalServer"