# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ActNursesportal' do

pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Fabric'
pod 'Crashlytics'


  pod 'ReactNativeFabric', :path => '../node_modules/react-native-fabric'

end


