/*
FileName: index.js
Author :Parshant Nagpal
Description: Conatins all action Types for app 
Date : 9 January 2019
*/

export const INITIALIZED = "example.app.INITIALIZED";
export const ROOT_CHANGED = "example.app.ROOT_CHANGED";
export const USER_REGISTERATION = "USER_REGISTERATION";
export const SET_NAVIGATOR = "SET_NAVIGATOR";
export const SET_COMPONENT = "SET_COMPONENT";
export const SET_SCREEN = "SET_SCREEN";

export const LOGOUT = "LOGOUT";
export const LOGIN = "LOGIN";

export const RESET_USER = "RESET_USER";

export const SAVE_USER = "SAVE_USER";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCESS = "LOGIN_SUCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const FORGOT_REQUEST = "FORGOT_REQUEST";
export const FORGOT_SUCESS = "FORGOT_SUCESS";
export const FORGOT_FAIL = "FORGOT_FAIL";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCESS = "CHANGE_PASSWORD_SUCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

export const START_LOADER = "START_LOADER";
export const STOP_LOADER = "STOP_LOADER";
export const START_REFRESH_LOADER = "START_REFRESH_LOADER";
export const STOP_REFRESH_LOADER = "STOP_REFRESH_LOADER";

export const SHOW_TOAST = "SHOW_TOAST";
export const HIDE_TOAST = "HIDE_TOAST";

export const OPEN_SHIFTS = "OPEN_SHIFTS";
export const ADD_MYSCHEDULE = "ADD_MYSCHEDULE";
export const POTIENTIAL_CASES = "POTIENTIAL_CASES";
export const CLEAR_POTIENTIAL_DATA = "CLEAR_POTIENTIAL_DATA";
export const CLEAR_OPEN_SHIFT = "CLEAR_OPEN_SHIFT";
export const CLEAR_MY_SCHEDULE = "CLEAR_MY_SCHEDULE";
export const UPDATE_POTIENTIAL_LIKE_INDICATOR =
  "UPDATE_POTIENTIAL_LIKE_INDICATOR";
export const UPDATE_OPENSHIFT_LIKE_INDICATOR =
  "UPDATE_OPENSHIFT_LIKE_INDICATOR";
export const PRINTABLE_FORMS = "PRINTABLE_FORMS";

export const SET_WEB_WIDTH = "SET_WEB_WIDTH";
